name: "Base Camp setup"
description: "Run before any of the basecamp actions"
runs:
  using: "composite"
  steps:
    # Ideally we would add the BaseCamp checkout, and the SSH agent setup here, but it's easier to use existing
    # actions for this. Once `uses:` is supported in composite actions, they will be moved here.
    - name: Apt requirements
      run: apt-get update && apt-get install build-essential rsync -y
      shell: bash

    - name: Install python code
      run: |
        pip install -U pip setuptools wheel
        pip install -U .[dev] --ignore-installed --use-feature=2020-resolver
        python -m spacy download en_core_web_sm
      shell: bash

    - name: Git config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
      shell: bash
