repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.20
    hooks:
      - id: isort
        types: [python]
        args:
          - "--multi-line=3"
          - "--trailing-comma"
          - "--force-grid-wrap=0"
          - "--use-parentheses"
          - "--line-width=88"
          - "--project"
          - "bioconda_cli"
          - "--thirdparty"
          - "conda"

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
