# This is the regular build workflow that runs tests and ensures PRs are not breaking things
name: Basecamp

on:
  schedule:
    # Run each monday at 12
    - cron: "0 12 * * MON"
  repository_dispatch:
    # Also run whenever we update aCLImatise
    types: [aclimatise-update]

jobs:
  build:
    container: continuumio/miniconda3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@v0.4.0
        name: Permission to push to BaseCamp
        with:
          ssh-private-key: ${{ secrets.BASECAMPDEPLOY }}

      - uses: actions/checkout@v2
        with:
          repository: aCLImatise/BaseCamp
          path: BaseCamp

      - name: Apt requirements
        run: apt-get update && apt-get install build-essential -y

      - name: Install python code
        run: |
          pip install -U pip setuptools wheel
          pip install -U .[dev] --ignore-installed --use-feature=2020-resolver
          python -m spacy download en

      - name: Update metadata
        run: |
          source /root/.bashrc
          # Check for the latest versions of tools etc
          aclimatise-automation metadata --test > BaseCamp/new_metadata.yml
        shell: bash

      - name: Reanalyse Definitions
        run: |
          source /root/.bashrc
          # If the parser is newer, update the definitions
          aclimatise-automation reanalyse BaseCamp/ToolDefinitions --old-meta BaseCamp/metadata.yml
        shell: bash

      - name: aCLImatise New Versions
        run: |
          source /root/.bashrc
          # Analyse new packages and/or versions of packages
          aclimatise-automation install BaseCamp/new_metadata.yml BaseCamp/ToolDefinitions --last-meta BaseCamp/metadata.yml
        shell: bash

      - name: Regenerate Wrappers
        run: |
          source /root/.bashrc
          # Regenerate all wrappers
          aclimatise-automation wrappers BaseCamp/ToolDefinitions -o BaseCamp/ToolWrappers
        shell: bash

      - name: Move metadata file
        run: |
          source /root/.bashrc
          # The new metadata is now the current metadata
          mv BaseCamp/new_metadata.yml BaseCamp/metadata.yml
        shell: bash

      - name: Commit files
        run: |
          cd BaseCamp
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update BaseCamp"
          git push origin master
