# This is the regular build workflow that runs tests and ensures PRs are not breaking things
name: Basecamp

on:
  schedule:
    # Run each monday at 12
    - cron: "0 12 * * MON"
  repository_dispatch:
    # Also run whenever we update aCLImatise
    types: [aclimatise-update]

jobs:
  metadata:
    container: continuumio/miniconda3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@v0.4.1
        name: Permission to push to BaseCamp
        with:
          ssh-private-key: ${{ secrets.BASECAMPDEPLOY }}

      - uses: actions/checkout@v2
        with:
          repository: aCLImatise/BaseCamp
          path: BaseCamp
          ssh-key: ${{ secrets.BASECAMPDEPLOY }}

      - uses: ./.github/actions/setup
        name: Setup

      - name: Update metadata
        run: |
          source /root/.bashrc
          # Check for the latest versions of tools etc
          aclimatise-automation metadata --filter-r > BaseCamp/new_metadata.yml
        shell: bash

      - name: Upload metadata
        uses: actions/upload-artifact@v2
        with:
          name: metadata
          path: BaseCamp/new_metadata.yml

  reanalyse:
    container: continuumio/miniconda3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@v0.4.1
        name: Permission to push to BaseCamp
        with:
          ssh-private-key: ${{ secrets.BASECAMPDEPLOY }}

      - uses: actions/checkout@v2
        with:
          repository: aCLImatise/BaseCamp
          path: BaseCamp
          ssh-key: ${{ secrets.BASECAMPDEPLOY }}

      - uses: ./.github/actions/setup
        name: Setup

      - uses: actions/download-artifact@v2

      - name: Reanalyse Definitions
        run: |
          source /root/.bashrc
          # If the parser is newer, update the definitions
          aclimatise-automation reanalyse BaseCamp/ToolDefinitions --old-meta BaseCamp/metadata.yml --new-meta BaseCamp/new_metadata.yml --wrapper-root BaseCamp/ToolWrappers
        shell: bash

      - name: Upload reanalysis
        uses: actions/upload-artifact@v2
        with:
          name: reanalysis
          path: |
            BaseCamp/ToolDefinitions
            BaseCamp/ToolWrappers

  new_tools:
    container: continuumio/miniconda3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@v0.4.1
        name: Permission to push to BaseCamp
        with:
          ssh-private-key: ${{ secrets.BASECAMPDEPLOY }}

      - uses: actions/checkout@v2
        with:
          repository: aCLImatise/BaseCamp
          path: BaseCamp
          ssh-key: ${{ secrets.BASECAMPDEPLOY }}

      - uses: ./.github/actions/setup
        name: Setup

      - uses: actions/download-artifact@v2

      - name: aCLImatise New Versions
        run: |
          source /root/.bashrc
          # Analyse new packages and/or versions of packages
          aclimatise-automation install BaseCamp/new_metadata.yml BaseCamp/ToolDefinitions --last-meta BaseCamp/metadata.yml --wrapper-root BaseCamp/ToolWrappers
          cd BaseCamp
          git add ToolDefinitions ToolWrappers
          git commit -m "aCLImatise new packages, reanalyse old packages" || true
        shell: bash

      - name: Move metadata file
        run: |
          source /root/.bashrc
          # The new metadata is now the current metadata
          mv BaseCamp/new_metadata.yml BaseCamp/metadata.yml
          cd BaseCamp
          git add metadata.yml
          git commit -m "Update metadata file" || true
        shell: bash

      - name: Commit files
        run: |
          cd BaseCamp
          git push origin master
