# This is the regular build workflow that runs tests and ensures PRs are not breaking things
name: CI

on:
  # Also run whenever we push
  [push, pull_request]

jobs:
  build:
    container: continuumio/miniconda3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup
        name: Setup

      - uses: pre-commit/action@v2.0.0

      - name: Test CLI
        run: |
          source /root/.bashrc
          aclimatise-automation metadata --test > packages.yml
          mkdir defs/ wraps/
          aclimatise-automation install packages.yml defs/ --wrapper-root wraps/
          aclimatise-automation wrappers defs/ --output-dir wraps/
          aclimatise-automation reanalyse defs/ --wrapper-root wraps/
        shell: bash
