# This is the regular build workflow that runs tests and ensures PRs are not breaking things
name: CI

on:
  # Also run whenever we push
  [push, pull_request]

jobs:
  build:
    container: continuumio/miniconda3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Apt requirements
        run: apt-get update && apt-get install build-essential -y

      - name: Install python code
        run: |
          pip install -U pip setuptools wheel
          pip install -U .[dev] --ignore-installed --use-feature=2020-resolver
          python -m spacy download en

      - uses: pre-commit/action@v1.0.1

      - name: Test CLI
        run: |
          source /root/.bashrc
          aclimatise-automation metadata --test > packages.yml
          mkdir out/
          aclimatise-automation install packages.yml out/
          aclimatise-automation wrappers out/
          aclimatise-automation reanalyse out/
        shell: bash
