name: CI

on:
  # Run on the first of every month
  schedule:
    - cron: "0 0 1 * *"

  # Also run whenever we push
  push:

jobs:
  build:
    container: continuumio/miniconda3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Apt requirements
        run: apt-get update && apt-get install build-essential -y

      - name: Install python code
        run: |
          pip install -U pip setuptools wheel
          pip install -U .[dev]

      - uses: pre-commit/action@v1.0.1
