name: CI

on:
  # Run on the first of every month
  schedule:
    - cron:  '0 0 1 * *'

  # Also run whenever we push
  push:

jobs:
  build:
    container: continuumio/miniconda3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install python code
        run: |
          pip install -U pip setuptools wheel
          pip install -U .

      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.ToolDefinitionDeploy }}

      - name: List all bioconda packages
        run: find_cli env-dump > packages.txt

      - uses: actions/checkout@v2
        name: Checkout the tool repository
        with:
          path: ToolDefinitions
          ref: master
          repository: acclimatise/ToolDefinitions
          ssh-key: ${{ secrets.ToolDefinitionDeploy }}

      - name: Clear existing definitions
        run: rm ToolDefinitions/*.yml
#
#      - name: Checkout the tool repository
#        run: |
#          git clone "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"

      - name: Install packages and acclimatise everything
        # We have to manually source .bashrc https://stackoverflow.com/a/37286648/2148718
        run: |
          source /root/.bashrc
          find_cli acclimatise ToolDefinitions packages.txt
        shell: bash

      - name: Commit files
        run: |
          cd ToolDefinitions
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update"
          git config --local --unset-all "http.https://github.com/.extraheader"
          git push origin master

#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          repository: acclimatise/ToolDefinitioning
#          directory: ToolDefinitions
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#
      - name: Cache conda environment
        uses: actions/cache@v1
        env:
          cache-name: cache-conda
        with:
          path: /opt/conda
          key: always-cache
