name: CI

on:
  # Also run whenever we push
  [push, pull_request]

jobs:
  build:
    container: continuumio/miniconda3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Apt requirements
        run: apt-get update && apt-get install build-essential -y

      - name: Install python code
        run: |
          pip install -U pip setuptools wheel
          pip install -U .[dev] --ignore-installed
          python -m spacy download en

      - uses: pre-commit/action@v1.0.1

      - name: Test CLI
        run: |
          source /root/.bashrc
          aclimatise-automation list-packages --test > packages.txt
          mkdir out/
          aclimatise-automation install packages.txt out/
          aclimatise-automation wrappers out/
        shell: bash
